### ISSUE TITLE
import statement outdated?

### ISSUE THREAD

**Issue by sshameer** [brianjamesschmidt/gim3e#3]
Hi 

I found "**..flux_analysis.objective import update_objective**" in **gim3e_optimize** function from gim3e.core.gim3e.py

I think the latest version of cobrapy does not have "objective" in "flux_analysis"

Thank you for this package
Keep up the good work
Sanu

---

result = gim3e.gim3e(cobra_model,expData)
Switched solver from cplex to glpk.
Determining the best objective value...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gim3e-1.0.3-py2.7.egg/gim3e/core/gim3e.py", line 148, in gim3e
    tolerance_integer = tolerance_integer)
  File "/usr/local/lib/python2.7/dist-packages/gim3e-1.0.3-py2.7.egg/gim3e/core/gim3e.py", line 2047, in gim3e_optimize
    from cobra.flux_analysis.objective import update_objective

**Comment by sshameer** [comment]
Hi aebrahim

Thanks for the quick response :+1:
I think you missed deleting the import statement at **line 2047**

unless the import statement is not deleted, the error seems to remain

result = gim3e.gim3e(cobra_model,expData)
Switched solver from cplex to glpk.
Determining the best objective value...
Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib/python2.7/dist-packages/gim3e-1.0.3-py2.7.egg/gim3e/core/gim3e.py", line 148, in gim3e
tolerance_integer = tolerance_integer)
File "/usr/local/lib/python2.7/dist-packages/gim3e-1.0.3-py2.7.egg/gim3e/core/gim3e.py", line 2047, in gim3e_optimize
from cobra.flux_analysis.objective import update_objective
ImportError: No module named objective

Deleting the import fixes this issue
