### ISSUE TITLE
Examples fail

### ISSUE THREAD

**Issue by bollepel** [brianjamesschmidt/gim3e#8]
I'm totally new to GIM3E, so I tried the examples from the examples folder. I changed the solver to gurobi as I don't have a cplex license and sadle both examples give errors concerning turnover metabolites.

01_run_gim3e_with_salmonella.py results in the following output/error:

Determining the best objective value...
No parameters matching 'the_problem' found
... OK
Converting to irreversible...
cobra/core/Reaction.py:192 UserWarning: Setting reaction reversibility is ignored
... OK
Adding turnover metabolites...
No parameters matching 'the_problem' found
No parameters matching 'the_problem' found
No parameters matching 'the_problem' found
No parameters matching 'the_problem' found
No parameters matching 'the_problem' found
Traceback (most recent call last):
  File "01_run_gim3e_with_salmonella.py", line 88, in <module>
    trim_model = False, solver = 'gurobi')
  File "/usr/local/lib/python2.7/dist-packages/gim3e-1.0.2-py2.7.egg/gim3e/core/gim3e.py", line 244, in gim3e
    FVA_verbose = False)
  File "/usr/local/lib/python2.7/dist-packages/gim3e-1.0.2-py2.7.egg/gim3e/core/gim3e.py", line 2411, in test_turnover_metabolite_constraints
    verbose = FVA_verbose)
  File "/usr/local/lib/python2.7/dist-packages/gim3e-1.0.2-py2.7.egg/gim3e/core/gim3e.py", line 1057, in irreversible_flux_variability_analysis
    the_index = the_reactions.index(the_reaction.id)
ValueError: 'TMS_26dap__LL_c' is not in list

The second example, 02_sample_core_gim3e.py results in:
cobra/io/sbml.py:83 UserWarning: print_time is deprecated
8.39
No parameters matching 'the_problem' found
Determining the best objective value...
No parameters matching 'the_problem' found
... OK
Converting to irreversible...
cobra/core/Reaction.py:192 UserWarning: Setting reaction reversibility is ignored
... OK
No microarray data given, not imposing constraint based on intensity data.
About to run FVA.
No parameters matching 'the_problem' found
No parameters matching 'the_problem' found
No parameters matching 'the_problem' found
Traceback (most recent call last):
  File "02_sample_core_gim3e.py", line 54, in <module>
    trim_model = False, solver = 'gurobi')
  File "/usr/local/lib/python2.7/dist-packages/gim3e-1.0.2-py2.7.egg/gim3e/core/gim3e.py", line 372, in gim3e
    verbose = FVA_verbose)
  File "/usr/local/lib/python2.7/dist-packages/gim3e-1.0.2-py2.7.egg/gim3e/core/gim3e.py", line 1057, in irreversible_flux_variability_analysis
    the_index = the_reactions.index(the_reaction.id)
ValueError: 'ACALD' is not in list

**Comment by bollepel** [comment]
I've found the issue. On line 1057 in gim3e.py the_reaction is already referring to a reaction id, and hence it has no attribute 'id'. Removing the .id solves the problem.
